coverage:
  status:
    project:
      default:
        threshold: 5%
        paths: src
        informational: true
    patch:
      default:
        threshold: 5%
        paths: src
        informational: true
