from typing import Any as _Any, Hashable, Optional, NoReturn

from trafaret.dataerror import DataError


class TrafaretMeta(type):
    def __or__(cls, other): ...
    def __and__(cls, other): ...
    def __rshift__(cls, other): ...

class Trafaret(metaclass=TrafaretMeta):
    def check(self, value: _Any, context: Optional[_Any] = ...) -> _Any: ...
    def _failure(self, error: str = None, value: _Any = ...) -> NoReturn: ...
    def append(self, other): ...
    def __or__(self, other): ...
    def __and__(self, other): ...
    def __rshift__(self, other): ...
    def __call__(self, val, context=None): ...

class Key:
    def __init__(self, name: Hashable,
                 default: _Any = ...,
                 optional: bool = False,
                 to_name: Hashable = None,
                 trafaret: Trafaret = None) -> None: ...
    def get_name(self) -> Hashable: ...
    ...

def ensure_trafaret(trafaret): ...

class TypeMeta(TrafaretMeta):
    def __getitem__(self, type_): ...

class NumberMeta(TrafaretMeta):
    def __getitem__(cls, slice_): ...
    def __lt__(cls, lt): ...
    def __gt__(cls, gt): ...

class SquareBracketsMeta(TrafaretMeta):
    def __getitem__(self, args): ...

class OnError(Trafaret): ...
class TypingTrafaret(Trafaret, metaclass=TypeMeta): ...
class Subclass(TypingTrafaret): ...
class Type(TypingTrafaret): ...
class Any(Trafaret): ...
class And(Trafaret): ...
class Or(Trafaret): ...

class FloatRaw(Trafaret, metaclass=NumberMeta): ...
class Float(FloatRaw): ...
class IntRaw(FloatRaw): ...
class Int(IntRaw): ...
class Dict(Trafaret):
    def __init__(self, *args, **trafarets): ...
    def allow_extra(self, *names, **kw): ...
    def ignore_extra(self, *names): ...
class DictKeys(Trafaret): ...
class Mapping(Trafaret):
    def __init__(self, key, value): ...
class Enum(Trafaret):
    def __init__(self, *variants): ...
class Callable(Trafaret): ...
class Call(Trafaret):
    def __init__(self, fn): ...
class Forward(Trafaret): ...
class List(Trafaret, metclass=SquareBracketsMeta):
    def __init__(self, trafaret, min_length=0, max_length=None): ...
class Tuple(Trafaret):
    def __init__(self, *args): ...
class Atom(Trafaret): ...
class String(Trafaret):
    def __init__(self, allow_blank=False, min_length=None, max_length=None): ...
class Bytes(Trafaret):
    def __init__(self, encoding: str = 'utf-8'): ...
class Null(Trafaret): ...
class Bool(Trafaret): ...
class StrBool(Trafaret): ...

def guard(trafaret=None, **kwargs): ...
def ignore(val): ...
def catch(checker, *a, **kw): ...
def extract_error(checker, *a, **kw): ...

class GuardError(DataError): ...
